name: Build and populate cache

on:
  workflow_dispatch:
  push:
    paths:
      - wallpapers/**/*

jobs:
  build:
    name: Build (${{ matrix.system }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin
          - os: ubuntu-24.04-arm
            system: aarch64-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: https://install.lix.systems/lix/lix-installer-${{ matrix.system }}
          logger: pretty

      - name: Setup cachix
        uses: cachix/cachix-action@v13
        with:
          name: everviolet
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build from the matrix
        run: nix build -L .#full
