name: Build and populate cache

on:
  workflow_dispatch:
  push:
    paths:
      - wallpapers/**/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Setup cachix
        uses: cachix/cachix-action@v13
        with:
          name: everviolet
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build from the matrix
        run: nix build -L .#full
