name: "build and deploy"

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Setup cachix
        uses: cachix/cachix-action@v13
        with:
          name: everviolet
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build from the matrix
        run: nix build -L .#full

      - run: tar czf wallpapers.tar.gz --directory=result/share/wallpapers .

      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wallpapers-result
          path: wallpapers.tar.gz

  build-site:
    name: "build site"
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: wallpapers-result

      - run: mkdir -p result/share/wallpapers && tar xvf wallpapers.tar.gz -C result/share/wallpapers

      - name: install, build, and upload site
        uses: withastro/action@v3
        with:
          path: site

  deploy-site:
    name: "deploy site"
    needs: build-site
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
